// Copyright (c) Josef Pihrt and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator.CSharp
{
    public static partial class AnalyzerOptions
    {
        internal static readonly AnalyzerOptionDescriptor SuppressUnityScriptMethods = new AnalyzerOptionDescriptor("roslynator.RCS1213.suppress_unity_script_methods", DiagnosticRules.RemoveUnusedMemberDeclaration);
        internal static readonly AnalyzerOptionDescriptor UseComparisonInsteadPatternMatchingToCheckForNull = new AnalyzerOptionDescriptor("roslynator.RCS1248.invert", DiagnosticRules.UsePatternMatchingToCheckForNullOrViceVersa);
    }
}