// Copyright (c) Josef Pihrt and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

using System.Collections.Generic;

namespace Roslynator
{
    public static partial class ConfigOptions
    {
        public static readonly ConfigOptionDescriptor MaxLineLength = new(key: ConfigOptionKeys.MaxLineLength, defaultValue: "140", defaultValuePlaceholder: "<MAX_LINE_LENGTH>", description: "Max line length");
        public static readonly ConfigOptionDescriptor PreferExplicitlyTypedArray = new(key: ConfigOptionKeys.PreferExplicitlyTypedArray, defaultValue: null, defaultValuePlaceholder: "true|false", description: "Prefer explicitly typed array");
        public static readonly ConfigOptionDescriptor PreferImplicitlyTypedArray = new(key: ConfigOptionKeys.PreferImplicitlyTypedArray, defaultValue: null, defaultValuePlaceholder: "true|false", description: "Prefer implicitly typed array");
        public static readonly ConfigOptionDescriptor PreferImplicitlyTypedArrayWhenTypeIsObvious = new(key: ConfigOptionKeys.PreferImplicitlyTypedArrayWhenTypeIsObvious, defaultValue: null, defaultValuePlaceholder: "true|false", description: "Prefer implicitly typed array when type is obvious");
        public static readonly ConfigOptionDescriptor PreferNewLineAtEndOfFile = new(key: ConfigOptionKeys.PreferNewLineAtEndOfFile, defaultValue: null, defaultValuePlaceholder: "true|false", description: "Prefer new line at the end of a file");
        public static readonly ConfigOptionDescriptor PreferParenthesesWhenCreatingNewObject = new(key: ConfigOptionKeys.PreferParenthesesWhenCreatingNewObject, defaultValue: null, defaultValuePlaceholder: "true|false", description: "Prefer parentheses when creating new object");
        public static readonly ConfigOptionDescriptor PrefixFieldIdentifierWithUnderscore = new(key: ConfigOptionKeys.PrefixFieldIdentifierWithUnderscore, defaultValue: "false", defaultValuePlaceholder: "true|false", description: "Prefix field identifier with underscore");
        private static IEnumerable<KeyValuePair<string, string>> GetRequiredOptions()
        {
            yield return new KeyValuePair<string, string>("RCS1014", JoinOptionKeys(ConfigOptionKeys.PreferExplicitlyTypedArray, ConfigOptionKeys.PreferImplicitlyTypedArray, ConfigOptionKeys.PreferImplicitlyTypedArrayWhenTypeIsObvious));
            yield return new KeyValuePair<string, string>("RCS1050", JoinOptionKeys(ConfigOptionKeys.PreferParenthesesWhenCreatingNewObject));
            yield return new KeyValuePair<string, string>("RCS0058", JoinOptionKeys(ConfigOptionKeys.PreferNewLineAtEndOfFile));
        }
    }
}