// Copyright (c) Josef Pihrt and Contributors. Licensed under the Apache License, Version 2.0. See License.txt in the project root for license information.

// <auto-generated>

namespace Roslynator
{
    public static partial class LegacyConfigOptions
    {
        public static readonly ConfigOptionDescriptor AddNewLineAfterBinaryOperatorInsteadOfBeforeIt = new(key: "roslynator.RCS0027.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor AddNewLineAfterConditionalOperatorInsteadOfBeforeIt = new(key: "roslynator.RCS0028.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor AddNewLineAfterEqualsSignInsteadOfBeforeIt = new(key: "roslynator.RCS0052.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor AddNewLineAfterExpressionBodyArrowInsteadOfBeforeIt = new(key: "roslynator.RCS0032.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor ConvertBitwiseOperationToHasFlagCall = new(key: "roslynator.RCS1096.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor ConvertExpressionBodyToBlockBody = new(key: "roslynator.RCS1016.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor ConvertExpressionBodyToBlockBodyWhenDeclarationIsMultiLine = new(key: "roslynator.RCS1016.use_block_body_when_declaration_is_multiline", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor ConvertExpressionBodyToBlockBodyWhenExpressionIsMultiLine = new(key: "roslynator.RCS1016.use_block_body_when_expression_is_multiline", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor ConvertMethodGroupToAnonymousFunction = new(key: "roslynator.RCS1207.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor DoNotRenamePrivateStaticFieldToCamelCaseWithUnderscore = new(key: "roslynator.RCS1045.suppress_when_field_is_static", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor DoNotSimplifyConditionalExpressionWhenConditionIsInverted = new(key: "roslynator.RCS1104.suppress_when_condition_is_inverted", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor DoNotUseElementAccessWhenExpressionIsInvocation = new(key: "roslynator.RCS1246.suppress_when_expression_is_invocation", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveAccessibilityModifiers = new(key: "roslynator.RCS1018.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveCallToConfigureAwait = new(key: "roslynator.RCS1090.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveEmptyLineBetweenClosingBraceAndSwitchSection = new(key: "roslynator.RCS1036.remove_empty_line_between_closing_brace_and_switch_section", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveEmptyLineBetweenSingleLineAccessors = new(key: "roslynator.RCS0011.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveEmptyLineBetweenUsingDirectivesWithDifferentRootNamespace = new(key: "roslynator.RCS0015.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveNewLineBetweenClosingBraceAndWhileKeyword = new(key: "roslynator.RCS0051.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveParenthesesFromConditionOfConditionalExpressionWhenExpressionIsSingleToken = new(key: "roslynator.RCS1051.do_not_parenthesize_single_token", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor RemoveParenthesesWhenCreatingNewObject = new(key: "roslynator.RCS1050.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor SuppressUnityScriptMethods = new(key: "roslynator.RCS1213.suppress_unity_script_methods", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor UseComparisonInsteadPatternMatchingToCheckForNull = new(key: "roslynator.RCS1248.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor UseImplicitlyTypedArray = new(key: "roslynator.RCS1014.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor UseImplicitlyTypedArrayWhenTypeIsObvious = new(key: "roslynator.RCS1014.use_implicit_type_when_obvious", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
        public static readonly ConfigOptionDescriptor UseStringEmptyInsteadOfEmptyStringLiteral = new(key: "roslynator.RCS1078.invert", defaultValue: "false", defaultValuePlaceholder: "true|false", description: "");
    }
}